'use client';

import { useState, type ReactNode } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronDown, CreditCard, Droplets, FileText, Heart, Mail, MessageCircle, PackageCheck, PackageOpen, Ruler, Search, ShieldCheck, Shirt, Truck } from 'lucide-react';
import type { StoreSettings } from '@/lib/supabase-store';
import { money } from '@/lib/catalog';
import { ActivityPrivacySetting } from './visitor-activity';

const pages = [
  ['shipping', 'Delivery', Truck], ['returns', 'Returns & exchanges', PackageCheck],
  ['faq', 'Shopping FAQs', MessageCircle], ['fabric-care', 'Fabric & care', Shirt],
  ['contact', 'Contact ZYRA', Mail], ['privacy', 'Privacy', ShieldCheck],
  ['terms', 'Terms of sale', FileText], ['website-terms', 'Website terms', FileText],
] as const;
const titles: Record<string, [string, string, string]> = {
  shipping: ['From our door to yours.', 'Delivery information', 'Your delivery charge, courier and next steps. All in one place.'],
  returns: ['Let’s get the fit right.', 'Returns & size exchanges', 'A 7-day size exchange, with clear steps and no guesswork.'],
  faq: ['A little help goes a long way.', 'Shopping FAQs', 'Quick answers before you order, and help after it arrives.'],
  'fabric-care': ['Good fabric. A little care.', 'Fabric & care', 'Find your fit and give your favourite pieces the care they need.'],
  contact: ['Talk to us.', 'Contact ZYRA', 'A question about a piece? Need help with an order? Start here.'],
  privacy: ['Your information, explained.', 'Privacy policy', 'What we use, why we need it and how to ask us about it.'],
  terms: ['Know before you order.', 'Terms of sale', 'The details that matter when shopping with ZYRA in Pakistan.'],
  'website-terms': ['A few ground rules.', 'Website terms', 'Using our store, sharing a review and keeping your account safe.'],
};
function Card({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) {
  return <article className="care-card"><i>{icon}</i><h3>{title}</h3><div>{children}</div></article>;
}
function Block({ id, title, children }: { id: string; title: string; children: ReactNode }) {
  return <section className="care-block" id={id}><h2>{title}</h2>{children}</section>;
}
const faqItems = [
  ['Sizing', 'How do I choose my size?', 'Open the size guide on the product page. Compare the garment measurements with a similar item you already own. If measurements are missing, ask us before ordering.'],
  ['Sizing', 'Are all ZYRA pieces the same fit?', 'No. Fit depends on the style. An oversized tee and a regular-fit piece will sit differently, so check the individual product details.'],
  ['Orders', 'How can I pay?', 'Cash on delivery and bank transfer are available. Any enabled online payment options appear at checkout. Review the final total before placing your order.'],
  ['Orders', 'Can I change or cancel my order?', 'Contact us with your order number as soon as possible. We can help with changes before dispatch; once an order is handed to a courier, changes may no longer be possible.'],
  ['Delivery', 'Which couriers do you use?', 'Our delivery partners include TCS, Protex, Leopards, M&P and Trax. The courier is selected according to your destination and service availability.'],
  ['Delivery', 'Can I open my parcel?', 'Ask us to confirm open-parcel availability for your order before dispatch. Inspection depends on the courier service booked; follow the rider’s instructions. It does not include wearing or using the item.'],
  ['Delivery', 'Where can I check my order?', 'Use Track your order with your order number and the email or phone entered at checkout. For a delayed or missed delivery, contact ZYRA with that order number.'],
  ['Exchanges', 'What is the exchange window?', 'Request a size exchange within 7 calendar days of delivery. Keep the item unworn, unwashed and with its tags. Replacement sizes are subject to availability.'],
  ['Exchanges', 'What if my item is wrong or damaged?', 'Contact us promptly with your order number and photos of the problem. Keep the packaging if possible. We will review the issue and arrange an appropriate replacement or refund.'],
];
function FAQs() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const matches = faqItems.filter(([group, question, answer]) => (category === 'All' || category === group) && `${question} ${answer}`.toLowerCase().includes(query.toLowerCase()));
  return <><label className="care-search"><Search aria-hidden="true" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search sizing, delivery, exchanges…" aria-label="Search shopping questions" /></label><div className="care-filters" role="group" aria-label="Question categories">{['All', 'Sizing', 'Orders', 'Delivery', 'Exchanges'].map(group => <button type="button" key={group} aria-pressed={category === group} onClick={() => setCategory(group)}>{group}</button>)}</div><p className="care-result-count" role="status">{matches.length} answers</p><div className="care-faqs">{matches.map(([group, question, answer]) => <details key={question}><summary><span><small>{group}</small>{question}</span><ChevronDown aria-hidden="true" /></summary><p>{answer}</p></details>)}</div>{!matches.length && <p>Try another word, or <a href="/pages/contact">ask the ZYRA team</a>.</p>}</>;
}
export function CustomerHelp({ path, settings }: { path: string; settings: StoreSettings }) {
  const key = path.split('/').pop() || 'contact';
  const content = titles[key];
  if (!content) return <main className="care-page"><h1>Looking for something?</h1><a href="/pages/contact">Visit customer help <ArrowRight /></a></main>;
  const [title, label, intro] = content;
  const email = settings.supportEmail;
  const whatsapp = settings.whatsappUrl && !settings.whatsappUrl.includes('923000000000') ? settings.whatsappUrl : null;
  const shipping = settings.flatShipping === 0 ? 'Free' : money(settings.flatShipping);
  return <main className={`care-page care-page-${key}`}>
    <nav className="care-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/pages/contact">Customer help</a><span>/</span><span aria-current="page">{label}</span></nav>
    <header className="care-hero"><div><p className="eyebrow">ZYRA / {label}</p><h1>{title}</h1><p>{intro}</p></div><div className="care-hero-mark" aria-hidden="true">{key === 'shipping' ? <Truck /> : key === 'returns' ? <PackageCheck /> : key === 'fabric-care' ? <Shirt /> : key === 'privacy' ? <ShieldCheck /> : key === 'contact' || key === 'faq' ? <MessageCircle /> : <FileText />}</div></header>
    <div className="care-layout"><aside className="care-nav"><p className="eyebrow">How can we help?</p><a href="/track-order"><PackageCheck />Track your order<ArrowUpRight /></a>{pages.map(([slug, name, Icon]) => <a href={`/pages/${slug}`} key={slug} aria-current={key === slug ? 'page' : undefined}><Icon aria-hidden="true" />{name}</a>)}</aside>
    <div className="care-content">
      {key === 'shipping' && <>
        <div className="care-card-grid"><Card icon={<Truck />} title="Standard delivery"><strong className="care-big">{shipping}</strong><p>{settings.freeShippingThreshold > 0 ? `Free on orders of ${money(settings.freeShippingThreshold)} or more.` : 'Check your delivery total at checkout.'}</p></Card><Card icon={<PackageOpen />} title="Open-parcel delivery"><p>Ask us to confirm availability for your order before dispatch.</p></Card></div>
        <Block id="couriers" title="Our delivery partners"><p>We work with the following couriers. Your parcel is assigned according to destination and service availability.</p><div className="care-couriers">{['TCS', 'Protex', 'Leopards', 'M&P', 'Trax'].map(name => <span key={name}><Truck aria-hidden="true" />{name}</span>)}</div></Block>
        <Block id="journey" title="What happens next"><ol className="care-steps"><li><b>Order received</b><p>Save your order number and check your delivery details.</p></li><li><b>Packed for you</b><p>Your order is prepared for dispatch. Bank-transfer orders need payment confirmation first.</p></li><li><b>On the way</b><p>Check your order status online. Contact us for the courier reference or a delivery update.</p></li></ol><a className="care-button" href="/track-order">Track your order <ArrowRight /></a></Block>
        <Block id="timing" title="Delivery timing & charges"><p>Delivery timing depends on your city, stock confirmation and courier coverage. Contact us before ordering if you need a piece by a specific date. A dispatch update is not a guaranteed arrival date.</p><p>Your delivery charge is shown before you place the order. If an address requires a different service or additional charge, we will ask you to agree before dispatch. Weather, holidays and courier disruptions can affect transit.</p></Block>
        <Block id="parcel" title="At your doorstep"><p>Keep your phone reachable and provide a complete address. For open-parcel service, confirm the arrangement with ZYRA before dispatch and follow the courier’s inspection process. Do not assume every courier or shipment supports it.</p><p>If the parcel looks damaged, is missing, or a delivery attempt fails, contact us with your order number. Photos of the outer packaging can help us investigate.</p></Block>
      </>}
      {key === 'returns' && <>
        <div className="care-card-grid"><Card icon={<PackageCheck />} title="Size exchanges"><strong className="care-big">7 days</strong><p>From delivery to request your exchange.</p></Card><Card icon={<Shirt />} title="Keep it unworn"><p>Unwashed, unused and with its tags. Keep the packaging where possible.</p></Card></div>
        <Block id="exchange" title="Three steps to a better fit"><ol className="care-steps"><li><b>Contact ZYRA</b><p>Send your order number, item name, current size and the size you need within 7 calendar days of delivery.</p></li><li><b>Get your return instructions</b><p>We confirm stock, the return address and courier charges. Please do not send a parcel before receiving instructions.</p></li><li><b>Send it back</b><p>Pack the item safely and keep the courier receipt. We check its condition before arranging the replacement.</p></li></ol></Block>
        <Block id="cost" title="Who pays for the courier?"><p>For a size preference change, the customer pays the return and replacement delivery charges. We will tell you the amount before you agree. For a confirmed wrong, damaged or defective item supplied by ZYRA, we cover the reasonable return and replacement delivery costs.</p><p>Replacement sizes depend on stock. If your requested size is unavailable, we will explain the options before proceeding.</p></Block>
        <Block id="problem" title="Wrong item or a quality issue?"><p>Contact us promptly with your order number and clear photos. Please avoid washing, altering or wearing the item after noticing the problem. Keep its packaging if available; an unboxing video is helpful but is not required to raise a concern.</p><p>After reviewing the issue, we will arrange an appropriate replacement or refund. The 7-day size-change policy does not remove any rights or remedies you have for defective or misdescribed goods under applicable law.</p></Block>
        <Block id="refunds" title="Refunds & cancellations"><p>For a change of mind or a preferred size, our standard offer is a size exchange. Contact us immediately if you need to cancel before dispatch. Once shipped, we may not be able to stop the parcel.</p><p>When a refund is agreed, we confirm the amount, method and expected processing time in writing. Online payments are normally returned through their payment route where supported. For cash-on-delivery orders, we arrange an agreed transfer method. Bank or payment-provider processing may take additional time. We do not replace a refund required by law with store credit without your agreement.</p></Block>
      </>}
      {key === 'faq' && <FAQs />}
      {key === 'fabric-care' && <>
        <div className="care-card-grid"><Card icon={<Heart />} title="Fabric comes first"><p>High-quality fabrics are central to ZYRA. Composition and feel vary by piece—check the individual product details.</p></Card><Card icon={<Ruler />} title="Find your fit"><p>Measure a garment you love, then compare it with the product’s size guide.</p></Card></div>
        <Block id="measure" title="Measure once. Choose with confidence."><ol className="care-steps"><li><b>Lay it flat</b><p>Use a similar garment that fits comfortably. Smooth it without stretching.</p></li><li><b>Compare the measurements</b><p>For tops, check chest width and length. For bottoms, check waist and inseam. Use the same units as the size guide.</p></li><li><b>Check the fit description</b><p>Oversized and regular styles fit differently. Ask us if the product’s measurements are not listed.</p></li></ol></Block>
        <Block id="wash" title="A simple care routine"><div className="care-card-grid"><Card icon={<Droplets />} title="Read the care label"><p>The garment label takes priority. Wash temperature and drying needs depend on the fabric.</p></Card><Card icon={<Shirt />} title="Protect the print"><p>Where the care label allows machine washing, turn graphic pieces inside out. Avoid ironing directly over prints.</p></Card></div><p>Separate colours and use a gentle detergent suitable for the garment. Avoid bleach unless the label specifically permits it. Follow the label for drying; ask us before using high heat on an unfamiliar fabric.</p></Block>
        <Block id="details" title="Want the fabric details?"><p>Send us the product name or link. We can help you check composition, fit and care before you order. We do not apply one fabric specification or shrinkage promise to every style.</p></Block>
      </>}
      {key === 'contact' && <>
        <div className="care-card-grid"><Card icon={<Mail />} title="Email the team"><p>For product questions, order support and privacy requests.</p><a className="care-contact-link" href={`mailto:${email}`}>{email}<ArrowUpRight /></a></Card><Card icon={<MessageCircle />} title={whatsapp ? 'Message on WhatsApp' : 'Find your order'}><p>{whatsapp ? 'Share your order number or the product you have a question about.' : 'Check the latest status using the details from checkout.'}</p><a className="care-contact-link" href={whatsapp || '/track-order'} {...(whatsapp ? { target: '_blank', rel: 'noreferrer' } : {})}>{whatsapp ? 'Open WhatsApp' : 'Track your order'}<ArrowUpRight /></a></Card></div>
        <Block id="message" title="Help us help you"><div className="care-message-list"><p><Check /><span><b>Before you buy</b>Product name or link, your size question and any fabric details you need.</span></p><p><Check /><span><b>About an order</b>Order number and the email or phone used at checkout.</span></p><p><Check /><span><b>Something isn’t right</b>A short description and relevant photos of the item or parcel.</span></p></div></Block>
        <Block id="safe" title="A quick note before you message"><p>Never send your card PIN, password, full card details or an OTP. We do not need these to help with an order. Only share delivery or payment-reference information through our confirmed support channels.</p><p>For a return, contact us first for the correct return address. Do not send parcels to an address taken from an old package without confirmation.</p></Block>
      </>}
      {key === 'privacy' && <>
        <div className="care-card-grid"><Card icon={<PackageCheck />} title="To fulfil your order"><p>Contact details, delivery address and the items you choose.</p></Card><Card icon={<ShieldCheck />} title="To support you"><p>Order references and messages needed to resolve your request.</p></Card></div>
        <Block id="information" title="Information we use"><p>ZYRA uses your name, email, phone, delivery address, order items, payment method and payment status to process purchases, arrange delivery and provide support. If you submit a review, the review and its public author details may appear on the site; your checkout contact details are not displayed as part of the review.</p></Block>
        <Block id="sharing" title="Who needs it"><p>Relevant order details are shared with the courier assigned to deliver your parcel, our hosting and order-storage providers, and the payment provider when you choose online payment. Support messages are also handled by the email or messaging provider you use. Some providers may process data outside Pakistan. Information may also be disclosed where required by law or to address fraud and security concerns.</p><p>Card-payment entry is handled by the payment provider. Do not send card details or OTPs to ZYRA support.</p></Block>
        <Block id="storage" title="Browser storage & site activity"><p>Your browser stores bag selections and privacy preferences. Checkout may keep a transaction reference to help resume a payment attempt. Product pages may use a session identifier to count recent product viewers.</p><p>ZYRA uses privacy-respecting store analytics and Google Analytics to understand page views, bag additions, checkout visits and completed orders. Analytics does not receive checkout form entries, passwords, card details or delivery addresses. Store activity identifiers expire after inactivity and store activity records are retained for up to 30 days. You can disable analytics below, and browser Do Not Track and Global Privacy Control signals are respected.</p><ActivityPrivacySetting /></Block>
        <Block id="retention" title="Retention & your requests"><p>Order and support information may need to be retained for fulfilment, accounting, complaints, fraud prevention and applicable legal requirements. Contact us to ask what information relates to your order, correct inaccurate details or request deletion. We may need to verify the request, and explain any records that must be retained.</p><p>Use <a href={`mailto:${email}`}>{email}</a> for privacy questions. Browser privacy preferences can be changed above; deleting browser storage may reset those preferences.</p></Block>
      </>}
      {key === 'terms' && <>
        <Block id="seller" title="Shopping with ZYRA"><p>These terms cover purchases from ZYRA through this store. Review the product description, selected size, colour, price, delivery charge and exchange policy before ordering. Contact <a href={`mailto:${email}`}>{email}</a> for seller details, an order query or a complaint.</p></Block>
        <Block id="prices" title="Prices & payment"><p>Prices are displayed in Pakistani rupees. The total, including the delivery charge and any applicable adjustments, is shown at checkout. Cash on delivery, bank transfer and any enabled online payment methods are presented there. Keep your order confirmation and payment reference.</p><p>A bank-transfer order requires payment verification. If there is a stock or pricing error, we will contact you to explain the options; we will not substitute an item or increase an agreed price without your consent. If we cannot fulfil a paid order, an appropriate refund will be arranged.</p></Block>
        <Block id="orders" title="Your order details"><p>Provide accurate contact and delivery information. Let us know promptly if something needs changing. An order reference records your request; payment and fulfilment status are shown separately. Dispatch depends on stock and any required payment confirmation.</p></Block>
        <Block id="aftercare" title="Delivery, exchanges & refunds"><p>Our <a href="/pages/shipping">delivery information</a> and <a href="/pages/returns">returns and exchange policy</a> form part of these terms. The voluntary size-exchange window is 7 calendar days from delivery for unworn items. It does not limit remedies available under law for a wrong, defective or misdescribed item.</p></Block>
        <Block id="rights" title="Your consumer rights"><p>Applicable Pakistani law governs these terms. Consumer protections can depend on the province or territory and the circumstances of the purchase. Nothing here excludes rights or remedies that cannot lawfully be excluded, or prevents you from contacting an appropriate consumer authority or court.</p><p>If something goes wrong, contact ZYRA with your order reference and the outcome you are seeking. Keep your receipt, correspondence and relevant photographs. We will review the issue and explain the next steps.</p></Block>
      </>}
      {key === 'website-terms' && <>
        <Block id="use" title="Using the store"><p>You may browse products, place genuine orders and use our customer-help tools. Do not interfere with the store, bypass access controls, misuse someone else’s information or submit fraudulent orders. Purchases are covered by our <a href="/pages/terms">terms of sale</a>.</p></Block>
        <Block id="content" title="Product images & information"><p>Product photographs help show the style and colour, but screens and lighting can affect appearance. Read the item’s description and size guide before ordering. This does not remove your rights if an item is materially different from its description.</p><p>ZYRA branding, photographs and written content may be protected by intellectual-property rights. Ask for permission before using store content commercially.</p></Block>
        <Block id="reviews" title="Reviews & messages"><p>Share an honest account of your own experience. Do not include private contact details, passwords, abusive content or material you do not have permission to share. Reviews may be moderated for privacy, relevance and misuse. A critical but relevant review should not be excluded merely because it is negative.</p></Block>
        <Block id="external" title="Other services & availability"><p>Payment, courier and social links may take you to services operated by other organisations. Their own terms and privacy notices apply there. If a page or checkout is unavailable, contact us for help; do not repeatedly submit payment without checking the status of the earlier attempt.</p></Block>
        <Block id="changes" title="Changes to these pages"><p>We may update website information and policies. Changes are not intended to remove rights attached to an existing order. For your purchase, keep the order confirmation and the policy information available when you placed it.</p></Block>
      </>}
      <section className="care-bottom"><div><p className="eyebrow">Still need a hand?</p><h2>We’re here for your next step.</h2></div><a className="care-button" href={key === 'contact' ? `mailto:${email}` : '/pages/contact'}>{key === 'contact' ? 'Email ZYRA' : 'Contact ZYRA'}<ArrowRight /></a></section>
    </div></div>
  </main>;
}
